# Generated by Django 6.1 on 2026-08-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_car_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_created', models.BooleanField(default=False)),
            ],
        ),
    ]
