# Generated by Django 6.1 on 2026-08-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_tovar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('nomi', models.CharField(blank=True, max_length=150, null=True)),
                ('puli', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oyiga_qancha', models.BooleanField(default=False)),
                ('necha_oyga', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RenameField(
            model_name='tovar',
            old_name='is_created',
            new_name='necha_oyga',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='price',
        ),
        migrations.AddField(
            model_name='tovar',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='nomi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='oyiga_qancha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tovar',
            name='puli',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
