# Generated by Django 6.1 on 2026-08-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_top_delete_car_rename_is_created_tovar_necha_oyga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='necha_oyga',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='top',
            name='oyiga_qancha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='necha_oyga',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='oyiga_qancha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
