# Generated by Django 6.1 on 2026-09-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_alter_top_necha_oyga_alter_top_oyiga_qancha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
